### PR TITLE
praxisdigital/moodle-block_sharing_cart#118

### PR DESCRIPTION
**Pull request by frederikmillingpytlick**
Merge praxisdigital/moodle-block_sharing_cart#118

### CODE REVIEW

**Comment by donhinkelman** [comment]
Thank you, Frederik. I merged this pull request. Is this a good time to make a Sharing Cart 4.3 release in the Plugins Database?

**Comment by frederikmillingpytlick** [comment]
@donhinkelman sure, just be aware that from now on, the sharing cart requires a minimum of PHP 7.4

**Comment by donhinkelman** [comment]
Thanks for pointing that out. I would have missed that important point.

**Comment by frederikmillingpytlick** [comment]
I just found a quick thing, could you wait with creating a new release? - I will let you know when it is fixed

**Comment by frederikmillingpytlick** [comment]
Everything looks good now :)

**Pull request merged**
