### PR TITLE
Added new setting to show "Copy Section"

### PR DESCRIPTION
**Pull request by AraPraxis**
#67 

[image](https://user-images.githubusercontent.com/89771146/226863986-05d454d3-df6d-403c-830a-b832a0e4f59d.png)

### CODE REVIEW

**Comment by donhinkelman** [comment]
Thanks, Anders. Shall I merge the pull request and test it on my 4.1 test server?

**Comment by donhinkelman** [comment]
What in particular should I look for in the changes you made?

**Comment by AraPraxis** [comment]
We've looked at some of the issues people have created on the sharing card, this one is a little old, but I've updated the "Copy section" as requested in this issue https://github.com/donhinkelman/moodle-block_sharing_cart/issues/67

**Comment by donhinkelman** [comment]
Is this a duplicate pull request of the #163?  I will merge the other one, test it on my test server and post the new version as Sharing Cart 4.1, release 1, because there so many changes. Thank you Anders!

**Comment by AraPraxis** [comment]
Pull Request #163 is the exact same update as this, but just on two different branches, as people use this master branch primarily, but we in praxis like to have more branches, to show the changes over the different Moodle versions 3.9, 3.10, 3.11, 4.0 etc.
Since this also works on 4.0, I'd think we could just call it 4.0 Release 6?

**Comment by donhinkelman** [comment]
Thank you, Anders. I hope I did do a mistake, as I am not a programmer. I just changed Readme and version.php to show the new release as Sharing Cart 4.1, release 1. However, when I tried upgrading on my own 4.1 test server, I got this error message. I think it is a problem with my test server, correct?
Screen Shot 2023-03-23 at 17 01 57
Screen Shot 2023-03-23 at 17 03 56

**Comment by AraPraxis** [comment]
It's no problem, I've resolved the changes, as it would be more correct to call it 4.1 Release 1

Could you try and reinstall the sharing cart on your test server? It should resolve the issue

**Comment by donhinkelman** [comment]
Thank you for the quick feedback. I merged the pull request and I will try to reinstall the sharing cart.

**Comment by donhinkelman** [comment]
I reinstalled, and it worked well. Thank you, Anders, for the quick adjustment. In my classic theme, the new section copy looks good. I hope everyone likes it. I notice that the old way of section copy is still there. That's good. Now I will make a new release for the Moodle Plugins Database.
Screen Shot 2023-03-23 at 18 07 21

**Comment by AraPraxis** [comment]
Ah, yes, might be good to insert into the notes that if the copy section is not there it's because an admin has disabled it. I'll add it together with some of the newer features/fixes that we'll do in the future! :)
Thanks!

**Comment by donhinkelman** [comment]
One more question. What caused the problem of the error? Was it a simple line in the version.php?  And why do we need to make a new "build" for 4.1?  I guess I am asking you to teach me about github. Thanks in advance.

**Comment by AraPraxis** [comment]
Yes, I do believe it was the "$plugin->requires" line in the version.php - I accidentally updated it to 4.0 and when it got changed back to 3.11.4, some errors occurred I believe, my bad.

In Praxis we have a lot of different branches to specific moodle version, hence the name MOODLE_40_STABLE etc., which is our complete "builds" for that moodle version and everything above that version. That way if we have a customer that runs Moodle 3.10 we can easily give them the correct branch/build, without errors, as specific code can be different from Moodle version to Moodle version or the "$plugin->requires" line, which also needs to be different. :)

I believe the intention for us pushing our branches into your sharing cart repository, is that at some point, we won't update older versions. At the moment we don't intent to update the plugin prior to 4.0, so the builds/branches can help people who are not fully ready to upgrade their Moodle version, to still use the plugin, as long as the correct branch is used :)

**Pull request merged**
