### PR TITLE
Fixed activities backup for flexible sections course format (#121)

### LINKED ISSUE #121: Basket icon not appearing when using non-standard course format setting
There seems to be an issue with the course format "flexible sections". In a course where I had enabled the Sharing Cart block, the basket icon only appeared beside sections, not activities. When I changed that to the standard "Topics" format, or to another non-standard format called "Tiles",  the basket icon then appeared beside individual activities/resources as well.

Moodle version 3.11.6+ (Build: 20220405)
Flexible section course format version 3.5.1  (2020051100)

### PR DESCRIPTION
**Pull request by Astor-Bizard**
Fixed basket icons not appearing for courses with the Flexible Sections format.
This fixes #121.

### CODE REVIEW

**Comment by donhinkelman** [comment]
Hi Astor-Bizard, thanks very much for sending this pull request. My apologies for not noticing it earlier. I have permissions to merge the request, however, I am not knowledgeable enough to know what to do with the conflicting files. Could you solve this conflict or tell me precisely what I should do?  Thanks!
Screen Shot 2022-08-30 at 10 46 42

**Comment by donhinkelman** [comment]
Wondering if the two conflicts need to be resolved before merging the pull request.

**Comment by Astor-Bizard** [comment]
Hi,
These .min.js and .min.js.map files are generated from the .js files located in the amd/src folder.
Usually we use grunt to generate them. I suppose there was a modification of them from another commit since I opened this pull request.
The best to do is maybe for you to :
- Pull the .js files from this PR,
- Re-generate the .min.js and .min.js.map files (this will totally rewrite them and resolve the conflict) using the tool you usually use.
I hope this helps you!

**Comment by frederikmillingpytlick** [comment]
Hi @Astor-Bizard,

For us to be able to merge this PR, your branch will need to be in sync with our master branch.

Steps:
1. Merge our [donhinkelman:master](https://github.com/donhinkelman/moodle-block_sharing_cart/tree/master) branch into your own [Astor-Bizard:master](https://github.com/Astor-Bizard/moodle-block_sharing_cart/tree/master) branch. 
2. Make sure to run `grunt amd` in the sharing_cart directory, so that the minified javascript is up to date. 
3. Commit the merge and push it to your branch. 

This should resolve the merge conflicts :)

**Comment by donhinkelman** [comment]
Thank you, Astor-Bizard, for the fixing the conflict. And for improving the appearance in the Flexible Sections course format.

**Comment by Astor-Bizard** [comment]
You're welcome!
Sorry it took a little while, I was trying to correctly configure my grunt installation... :)

**Pull request merged**
