### PR TITLE
Add Danish language file to the Sharing Cart, adjust the position of the add to cart icon, add support for format_pxflexsections and show tested course formats in the readme file

### PR DESCRIPTION
**Pull request by johnnypraxis**

### CODE REVIEW

**Comment by abias** [comment]
Hi @johnnypraxis ,

I have watched this pull request which was created and directly merged by you. While I fully appreciate that you start to support the sharing cart plugin, I would like to raise some concerns:

* You have merged a danish language pack into this plugin. This plugin ships with some language packs as legacy, but it has even more translations in AMOS where translations should go to (see https://moodle.org/plugins/translations.php?plugin=block_sharing_cart). 72% of the strings are already translated in AMOS into danish. Wouldn't it be better to remove all language packs from the plugin and transfer and merge the translations into AMOS as it is best practice?
* You have added special support for format_pxgrid and format_pxflexsections. These formats are not published in the Moodle plugin repo and they are also not findable on Github. For me, it feels weird to add this code then to this plugin, adding additional and unhelpful CSS code to every installation of this plugin. Could you please explain what these course formats are about?

Thank you in advance,
Alex

**Comment by johnnypraxis** [comment]
Hi Alexander

Thank you for looking into the commits.

1) You're right about the Danish language strings. I will make sure they are removed from the Sharing Cart plugin.

2) The Sharing Cart still contains bugs in official course formats. We would very much like to encourage people in the Moodle community to report bugs in course formats related to the Sharing Cart. This will allow support for as many course formats as possible and help users in the Moodle community. To be able to do that we need to add support for our internal course formats as well or we won't be able to install it on our servers. The course formats format_pxgrid and format_pxflexsections are just custom course formats by Praxis. They are modified versions of format_flexsections and format_grid from the Moodle plugins directory. Custom course formats sometimes require minor custom changes to the Sharing Cart plugin. Changes that don't affect other course formats. Same applies to our course formats. However, you are right again. It's not necessary to add custom CSS to the Sharing Cart. I will make sure those CSS changes are added directly to our own course formats and removed from the Sharing Cart plugin.

Do you prefer going through pull requests from us before they are released? At least in the beginning of our collaboration?

Best regards
Johnny Drud

**Comment by donhinkelman** [comment]
Thanks, Johnny, for explaining why you did those code additions. I am not so able to understand the process of good programming and code management yet, but your comments and Alex's questions are helping me get a better understanding.

**Comment by johnnypraxis** [comment]
I'm glad to hear that, @donhinkelman.

Thank you for getting back, @abias.

> But in the end, I would be more than grateful if this plugin would just be managed smoothly without my active participation and that's why, again, I am happy to see a Moodle partner joining the club.

That's just fine.

We will do our very best to maintain and improve the Sharing Cart plugin in the future. I'll let you know in case we need a second opinion.

Best regards
Johnny Drud

**Pull request merged**
