### PR TITLE
praxisdigital/moodle-block_sharing_cart#118

### PR DESCRIPTION
**Pull request by frederikmillingpytlick**
Merge praxisdigital/moodle-block_sharing_cart#118

### CODE REVIEW

**Comment by donhinkelman** [comment]
Sorry, I don't understand the "All checks have failed." message. Should I try merging this?

**Comment by frederikmillingpytlick** [comment]
@donhinkelman I've fixed the issue. The tests are now green :tada: 

This branch requires Moodle 4.2 or above - that is why the first check is failing. It tries to install the plugin on Moodle 4.1 - so that is expected.

I will merge it :)

**Comment by donhinkelman** [comment]
Ok, I will install in plugins database, noting that Moodle 4.2 is required. As well as PHP 7.2 or 7.4?

**Comment by donhinkelman** [comment]
Got it. Sharing Cart 4.4, release 3 requires Moodle 4.2 and PHP 8.0.

**Pull request merged**
