### PR TITLE
ISSUE_115: Add course module create instance

### PR DESCRIPTION
**Pull request by sharpchi**
For issue #115 it should be enough just to trigger the course_module_created event after being restored. I was thinking about creating a sharing cart event, but I think we're not so much interested in how it was created than the fact that it was and when.

### CODE REVIEW

**Comment by donhinkelman** [comment]
Hi sharpchi, and thanks for making this pull request.
Do you think that logging events will create a higher load, or memory problems?

**Comment by sharpchi** [comment]
No,  triggering the event is trivial, certainly compared to the task of creating a new activity from a backup.
It's also important to trigger the event if folk have observers watching, in case they need to do their own thing.

**Comment by donhinkelman** [comment]
Thank you, sharpchi, for the pull request, and apologies it took so long to merge it.

**Comment by sharpchi** [comment]
Sweet. Thanks.

**Pull request merged**
