### PR TITLE
Cover block_sharing_cart_plugins table by a metadata provider

### PR DESCRIPTION
**Pull request by golenkovm**
This is a fix for #85

### CODE REVIEW

**Comment by golenkovm** [comment]
Hi @sampraxis @donhinkelman 
Could you please have a look at this PR once you have a chance.
Cheers,
Mikhail

**Comment by donhinkelman** [comment]
Thanks, Mikhail, for providing this new code to merge. Sam or Johnny, this is beyond my expertise. Could you take a look and merge the request if it looks good to you?

**Comment by sampraxis** [comment]
We will look into it.

**Review by sampraxis — APPROVED** [review]

**Comment by sampraxis** [comment]
I have approved PR and everything seems fine.
I have no write permission to merge thing into the repository.
Could you do it @donhinkelman?

**Comment by donhinkelman** [comment]
OK, thanks, Sam for checking this out. I have merged it.

**Comment by donhinkelman** [comment]
Sam, you have also been invited to be a collaborator to this plugin.

**Comment by sampraxis** [comment]
Could you perhaps re-invite me again?
The previous invitation is already expired.

**Comment by golenkovm** [comment]
Cheers

**Pull request merged**
