### PR TITLE
Version 3.8 release 11 for Moodle version 3.8

### PR DESCRIPTION
**Pull request by sampraxis**
Related to the issue https://github.com/donhinkelman/moodle-block_sharing_cart/issues/10
And fixed and improved folder name creation.

### CODE REVIEW

**Comment by donhinkelman** [comment]
Thank you Sam, Mikkel and Johnny for your work on this--Sharing Cart Version 3.8, release 11. Does this improvement have any relation to Moodle 3.9?  In other words, has it been tested in Moodle 3.9? I have received questions about Sharing Cart in 3.9 but I have not tested it, and probably will not for a month or so.

**Comment by sampraxis** [comment]
Sorry, we haven't test it on moodle 3.9 yet.
But we will look into it.
By the way, we would like to add some unit testing and Travis CI automated testing, if that is ok with you?

**Comment by donhinkelman** [comment]
Thanks Sam for checking out 3.9 in the future. I am not a programmer so I don't know about unit testing and automated testing. The site, https://travis-ci.org/, looks good, so I trust you to go ahead. Will I need to learn something?

**Comment by sampraxis** [comment]
If you need some test, you can certainly read this documentation https://docs.moodle.org/dev/Travis_integration
The build for testing will be triggered by a new commit that was pushed (by default setting) and it will only run after .travis.yml instruction.
I will ensure that it have moodle 3.6 - 3.9 for testing in .travis.yml and add more unit testing to the plugin as well.

**Pull request merged**
